var = {'id': '77984068', 'premium': False, 'name': 'Курьер-водитель с личным автомобилем', 'department': None,
       'has_test': True, 'response_letter_required': False,
       'area': {'id': '1', 'name': 'Москва', 'url': 'https://api.hh.ru/areas/1'},
       'salary': {'from': 90000, 'to': None, 'currency': 'RUR', 'gross': True},
       'type': {'id': 'open', 'name': 'Открытая'}, 'address': None, 'response_url': None, 'sort_point_distance': None,
       'published_at': '2023-10-18T12:23:37+0300', 'created_at': '2023-10-18T12:23:37+0300', 'archived': False,
       'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=77984068',
       'show_logo_in_search': None, 'insider_interview': None, 'url': 'https://api.hh.ru/vacancies/77984068?host=hh.ru',
       'alternate_url': 'https://hh.ru/vacancy/77984068', 'relations': [],
       'employer': {'id': '2104558', 'name': 'GrowFood', 'url': 'https://api.hh.ru/employers/2104558',
                    'alternate_url': 'https://hh.ru/employer/2104558',
                    'logo_urls': {'original': 'https://hhcdn.ru/employer-logo-original/969143.jpeg',
                                  '240': 'https://hhcdn.ru/employer-logo/5496589.jpeg',
                                  '90': 'https://hhcdn.ru/employer-logo/5496588.jpeg'},
                    'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=2104558', 'accredited_it_employer': False,
                    'trusted': True},
       'snippet': {
        'requirement': 'Наличие личного легкового автомобиля. Действующие водительские права категории В. Наличие смартфона/планшета. Грамотная русская речь. Опыт работы водителем приветствуется. ',
        'responsibility': 'Доставка еды по заранее определенному маршруту. Информирование клиентов о доставке по телефону в день работы. Работа с установленной на телефон...'},
       'contacts': None, 'schedule': {'id': 'fullDay', 'name': 'Полный день'}, 'working_days': [],
       'working_time_intervals': [], 'working_time_modes': [], 'accept_temporary': False,
       'professional_roles': [{'id': '58', 'name': 'Курьер'}], 'accept_incomplete_resumes': False,
       'experience': {'id': 'between1And3', 'name': 'От 1 года до 3 лет'},
       'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False}