import pandas
import pandas as pd
import openpyxl
json_data = {'items': [
    {'id': '87542153', 'premium': False, 'name': 'Диспетчер чатов, удаленно', 'department': None, 'has_test': False,
     'response_letter_required': False, 'area': {'id': '113', 'name': 'Россия', 'url': 'https://api.hh.ru/areas/113'},
     'salary': {'from': 30000, 'to': 44000, 'currency': 'RUR', 'gross': True},
     'type': {'id': 'open', 'name': 'Открытая'}, 'address': None, 'response_url': None, 'sort_point_distance': None,
     'published_at': '2023-09-29T18:28:04+0300', 'created_at': '2023-09-29T18:28:04+0300', 'archived': False,
     'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=87542153', 'show_logo_in_search': None,
     'insider_interview': None, 'url': 'https://api.hh.ru/vacancies/87542153?host=hh.ru',
     'alternate_url': 'https://hh.ru/vacancy/87542153', 'relations': [],
     'employer': {'id': '1740', 'name': 'Яндекс', 'url': 'https://api.hh.ru/employers/1740',
                  'alternate_url': 'https://hh.ru/employer/1740',
                  'logo_urls': {'90': 'https://hhcdn.ru/employer-logo/3790847.png',
                                '240': 'https://hhcdn.ru/employer-logo/3790848.png',
                                'original': 'https://hhcdn.ru/employer-logo-original/837491.png'},
                  'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=1740', 'accredited_it_employer': False,
                  'trusted': True}, 'snippet': {
        'requirement': 'Опыт работы не требуется. Обязательно наличие ПК или ноутбука. Будет плюсом опыт работы на вакансиях:',
        'responsibility': None}, 'contacts': None, 'schedule': {'id': 'remote', 'name': 'Удаленная работа'},
     'working_days': [], 'working_time_intervals': [],
     'working_time_modes': [{'id': 'start_after_sixteen', 'name': 'Можно начинать работать после 16:00'}],
     'accept_temporary': False, 'professional_roles': [{'id': '40', 'name': 'Другое'}],
     'accept_incomplete_resumes': True, 'experience': {'id': 'noExperience', 'name': 'Нет опыта'},
     'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False},
    {'id': '87542199', 'premium': False, 'name': 'Оператор на входящие сообщения (удаленно, в Яндекс)',
     'department': None, 'has_test': False, 'response_letter_required': False,
     'area': {'id': '113', 'name': 'Россия', 'url': 'https://api.hh.ru/areas/113'},
     'salary': {'from': 30000, 'to': 44000, 'currency': 'RUR', 'gross': True},
     'type': {'id': 'open', 'name': 'Открытая'}, 'address': None, 'response_url': None, 'sort_point_distance': None,
     'published_at': '2023-09-29T18:30:48+0300', 'created_at': '2023-09-29T18:30:48+0300', 'archived': False,
     'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=87542199', 'show_logo_in_search': None,
     'insider_interview': None, 'url': 'https://api.hh.ru/vacancies/87542199?host=hh.ru',
     'alternate_url': 'https://hh.ru/vacancy/87542199', 'relations': [],
     'employer': {'id': '1740', 'name': 'Яндекс', 'url': 'https://api.hh.ru/employers/1740',
                  'alternate_url': 'https://hh.ru/employer/1740',
                  'logo_urls': {'90': 'https://hhcdn.ru/employer-logo/3790847.png',
                                '240': 'https://hhcdn.ru/employer-logo/3790848.png',
                                'original': 'https://hhcdn.ru/employer-logo-original/837491.png'},
                  'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=1740', 'accredited_it_employer': False,
                  'trusted': True}, 'snippet': {
        'requirement': 'Способен работать в команде. Способен принимать решения самостоятельно. Готов учиться и узнавать новое. Опыт работы в колл-центре или службе...',
        'responsibility': 'Работать с клиентами или партнерами для решения разнообразных ситуаций. Совершать звонки по их обращениям и давать письменные ответы. '},
     'contacts': None, 'schedule': {'id': 'remote', 'name': 'Удаленная работа'}, 'working_days': [],
     'working_time_intervals': [],
     'working_time_modes': [{'id': 'start_after_sixteen', 'name': 'Можно начинать работать после 16:00'}],
     'accept_temporary': False, 'professional_roles': [{'id': '40', 'name': 'Другое'}],
     'accept_incomplete_resumes': True, 'experience': {'id': 'noExperience', 'name': 'Нет опыта'},
     'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False},
    {'id': '87542103', 'premium': False, 'name': 'Менеджер чатов на дому (в Яндекс)', 'department': None,
     'has_test': False, 'response_letter_required': False,
     'area': {'id': '113', 'name': 'Россия', 'url': 'https://api.hh.ru/areas/113'},
     'salary': {'from': 30000, 'to': 44000, 'currency': 'RUR', 'gross': True},
     'type': {'id': 'open', 'name': 'Открытая'}, 'address': None, 'response_url': None, 'sort_point_distance': None,
     'published_at': '2023-09-29T18:23:45+0300', 'created_at': '2023-09-29T18:23:45+0300', 'archived': False,
     'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=87542103', 'show_logo_in_search': None,
     'insider_interview': None, 'url': 'https://api.hh.ru/vacancies/87542103?host=hh.ru',
     'alternate_url': 'https://hh.ru/vacancy/87542103', 'relations': [],
     'employer': {'id': '1740', 'name': 'Яндекс', 'url': 'https://api.hh.ru/employers/1740',
                  'alternate_url': 'https://hh.ru/employer/1740',
                  'logo_urls': {'90': 'https://hhcdn.ru/employer-logo/3790847.png',
                                '240': 'https://hhcdn.ru/employer-logo/3790848.png',
                                'original': 'https://hhcdn.ru/employer-logo-original/837491.png'},
                  'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=1740', 'accredited_it_employer': False,
                  'trusted': True}, 'snippet': {
        'requirement': 'Способен работать в команде. Способен принимать решения самостоятельно. Готов учиться и узнавать новое. Опыт работы в колл-центре или службе...',
        'responsibility': 'Работать с клиентами или партнерами для решения разнообразных ситуаций. Совершать звонки по их обращениям и давать письменные ответы. '},
     'contacts': None, 'schedule': {'id': 'remote', 'name': 'Удаленная работа'}, 'working_days': [],
     'working_time_intervals': [],
     'working_time_modes': [{'id': 'start_after_sixteen', 'name': 'Можно начинать работать после 16:00'}],
     'accept_temporary': False, 'professional_roles': [{'id': '40', 'name': 'Другое'}],
     'accept_incomplete_resumes': True, 'experience': {'id': 'noExperience', 'name': 'Нет опыта'},
     'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False},
    {'id': '87542065', 'premium': False, 'name': 'Менеджер чатов, удалённо (в Яндекс)', 'department': None,
     'has_test': False, 'response_letter_required': False,
     'area': {'id': '113', 'name': 'Россия', 'url': 'https://api.hh.ru/areas/113'},
     'salary': {'from': 30000, 'to': 44000, 'currency': 'RUR', 'gross': True},
     'type': {'id': 'open', 'name': 'Открытая'}, 'address': None, 'response_url': None, 'sort_point_distance': None,
     'published_at': '2023-09-29T18:21:19+0300', 'created_at': '2023-09-29T18:21:19+0300', 'archived': False,
     'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=87542065', 'show_logo_in_search': None,
     'insider_interview': None, 'url': 'https://api.hh.ru/vacancies/87542065?host=hh.ru',
     'alternate_url': 'https://hh.ru/vacancy/87542065', 'relations': [],
     'employer': {'id': '1740', 'name': 'Яндекс', 'url': 'https://api.hh.ru/employers/1740',
                  'alternate_url': 'https://hh.ru/employer/1740',
                  'logo_urls': {'90': 'https://hhcdn.ru/employer-logo/3790847.png',
                                '240': 'https://hhcdn.ru/employer-logo/3790848.png',
                                'original': 'https://hhcdn.ru/employer-logo-original/837491.png'},
                  'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=1740', 'accredited_it_employer': False,
                  'trusted': True}, 'snippet': {
        'requirement': 'Способен работать в команде. Способен принимать решения самостоятельно. Готов учиться и узнавать новое. Опыт работы в колл-центре или службе...',
        'responsibility': 'Работать с клиентами или партнерами для решения разнообразных ситуаций. Совершать звонки по их обращениям и давать письменные ответы. '},
     'contacts': None, 'schedule': {'id': 'remote', 'name': 'Удаленная работа'}, 'working_days': [],
     'working_time_intervals': [],
     'working_time_modes': [{'id': 'start_after_sixteen', 'name': 'Можно начинать работать после 16:00'}],
     'accept_temporary': False, 'professional_roles': [{'id': '40', 'name': 'Другое'}],
     'accept_incomplete_resumes': True, 'experience': {'id': 'noExperience', 'name': 'Нет опыта'},
     'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False},
    {'id': '87527250', 'premium': False, 'name': 'Менеджер по продажам (Тех-Серт)', 'department': None,
     'has_test': False, 'response_letter_required': False,
     'area': {'id': '1', 'name': 'Москва', 'url': 'https://api.hh.ru/areas/1'},
     'salary': {'from': 100000, 'to': None, 'currency': 'RUR', 'gross': False},
     'type': {'id': 'open', 'name': 'Открытая'}, 'address': None, 'response_url': None, 'sort_point_distance': None,
     'published_at': '2023-09-29T14:11:46+0300', 'created_at': '2023-09-29T14:11:46+0300', 'archived': False,
     'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=87527250', 'show_logo_in_search': None,
     'insider_interview': None, 'url': 'https://api.hh.ru/vacancies/87527250?host=hh.ru',
     'alternate_url': 'https://hh.ru/vacancy/87527250', 'relations': [],
     'employer': {'id': '827187', 'name': 'BY business group', 'url': 'https://api.hh.ru/employers/827187',
                  'alternate_url': 'https://hh.ru/employer/827187',
                  'logo_urls': {'original': 'https://hhcdn.ru/employer-logo-original/942457.jpg',
                                '240': 'https://hhcdn.ru/employer-logo/4210365.jpeg',
                                '90': 'https://hhcdn.ru/employer-logo/4210364.jpeg'},
                  'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=827187', 'accredited_it_employer': False,
                  'trusted': True}, 'snippet': {
        'requirement': 'Опыт в продажах B2B. Высшее/неполное высшее образование. Высокий уровень дисциплины. Хорошие коммуникативные навыки. Грамотный письменный и устный...',
        'responsibility': 'Продажи услуг компании по РФ, СНГ по разработанным скриптам. Ведение коммерческих переговоров с первыми лицами компаний, заключение сделок. '},
     'contacts': None, 'schedule': {'id': 'fullDay', 'name': 'Полный день'}, 'working_days': [],
     'working_time_intervals': [], 'working_time_modes': [], 'accept_temporary': False,
     'professional_roles': [{'id': '70', 'name': 'Менеджер по продажам, менеджер по работе с клиентами'}],
     'accept_incomplete_resumes': False, 'experience': {'id': 'between1And3', 'name': 'От 1 года до 3 лет'},
     'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False},
    {'id': '88292347', 'premium': False, 'name': 'Сотрудник ресторана', 'department': None, 'has_test': False,
     'response_letter_required': False, 'area': {'id': '1', 'name': 'Москва', 'url': 'https://api.hh.ru/areas/1'},
     'salary': {'from': 50000, 'to': 70000, 'currency': 'RUR', 'gross': False},
     'type': {'id': 'open', 'name': 'Открытая'}, 'address': None, 'response_url': None, 'sort_point_distance': None,
     'published_at': '2023-10-23T14:35:51+0300', 'created_at': '2023-10-23T14:35:51+0300', 'archived': False,
     'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=88292347',
     'branding': {'type': 'CONSTRUCTOR', 'tariff': 'BASIC'}, 'show_logo_in_search': True, 'insider_interview': None,
     'url': 'https://api.hh.ru/vacancies/88292347?host=hh.ru', 'alternate_url': 'https://hh.ru/vacancy/88292347',
     'relations': [],
     'employer': {'id': '2059392', 'name': 'Додо Пицца (ООО ДПМ Север)', 'url': 'https://api.hh.ru/employers/2059392',
                  'alternate_url': 'https://hh.ru/employer/2059392',
                  'logo_urls': {'original': 'https://hhcdn.ru/employer-logo-original/1027053.png',
                                '240': 'https://hhcdn.ru/employer-logo/5728981.png',
                                '90': 'https://hhcdn.ru/employer-logo/5728980.png'},
                  'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=2059392', 'accredited_it_employer': False,
                  'trusted': True}, 'snippet': {'requirement': None,
                                                'responsibility': 'Готовить пиццу и закуски. Принимать продукты от поставщиков. Готовить ингредиенты для будущих пицц. Поддерживать порядок на кухне. Раскладывать заказы для...'},
     'contacts': None, 'schedule': {'id': 'fullDay', 'name': 'Полный день'}, 'working_days': [],
     'working_time_intervals': [
         {'id': 'from_four_to_six_hours_in_a_day', 'name': 'Можно работать сменами по\xa04–6 часов в\xa0день'}],
     'working_time_modes': [{'id': 'start_after_sixteen', 'name': 'Можно начинать работать после 16:00'}],
     'accept_temporary': False, 'professional_roles': [{'id': '94', 'name': 'Повар, пекарь, кондитер'}],
     'accept_incomplete_resumes': True, 'experience': {'id': 'noExperience', 'name': 'Нет опыта'},
     'employment': {'id': 'part', 'name': 'Частичная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False},
    {'id': '87790296', 'premium': False, 'name': 'Фасовщик навогодних подарков', 'department': None, 'has_test': False,
     'response_letter_required': False, 'area': {'id': '1002', 'name': 'Минск', 'url': 'https://api.hh.ru/areas/1002'},
     'salary': {'from': 1500, 'to': None, 'currency': 'BYR', 'gross': False},
     'type': {'id': 'open', 'name': 'Открытая'},
     'address': {'city': 'Минск', 'street': 'улица Солтыса', 'building': '187А', 'lat': 53.904687, 'lng': 27.641781,
                 'description': None, 'raw': 'Минск, улица Солтыса, 187А', 'metro': None, 'metro_stations': [],
                 'id': '11884727'}, 'response_url': None, 'sort_point_distance': None,
     'published_at': '2023-10-05T15:23:40+0300', 'created_at': '2023-10-05T15:23:40+0300', 'archived': False,
     'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=87790296', 'show_logo_in_search': None,
     'insider_interview': None, 'url': 'https://api.hh.ru/vacancies/87790296?host=hh.ru',
     'alternate_url': 'https://hh.ru/vacancy/87790296', 'relations': [],
     'employer': {'id': '3718843', 'name': 'Добрые Новости', 'url': 'https://api.hh.ru/employers/3718843',
                  'alternate_url': 'https://hh.ru/employer/3718843',
                  'logo_urls': {'original': 'https://hhcdn.ru/employer-logo-original/668275.jpg',
                                '240': 'https://hhcdn.ru/employer-logo/3114233.jpeg',
                                '90': 'https://hhcdn.ru/employer-logo/3114232.jpeg'},
                  'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=3718843', 'accredited_it_employer': False,
                  'trusted': True},
     'snippet': {'requirement': 'Наличие сан.книжки обязательно.', 'responsibility': None}, 'contacts': None,
     'schedule': {'id': 'fullDay', 'name': 'Полный день'}, 'working_days': [], 'working_time_intervals': [],
     'working_time_modes': [], 'accept_temporary': True, 'professional_roles': [{'id': '40', 'name': 'Другое'}],
     'accept_incomplete_resumes': False, 'experience': {'id': 'noExperience', 'name': 'Нет опыта'},
     'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False},
    {'id': '87907825', 'premium': False, 'name': 'Преподаватель английского языка', 'department': None,
     'has_test': False, 'response_letter_required': True,
     'area': {'id': '2759', 'name': 'Ташкент', 'url': 'https://api.hh.ru/areas/2759'},
     'salary': {'from': 4000000, 'to': 8000000, 'currency': 'UZS', 'gross': False},
     'type': {'id': 'open', 'name': 'Открытая'},
     'address': {'city': 'Ташкент', 'street': 'улица Хонзодабегим', 'building': '9/1', 'lat': 41.292390280222676,
                 'lng': 69.28308026256438, 'description': None, 'raw': 'Ташкент, улица Хонзодабегим, 9/1',
                 'metro': None, 'metro_stations': [], 'id': '11566679'}, 'response_url': None,
     'sort_point_distance': None, 'published_at': '2023-10-09T11:29:07+0300', 'created_at': '2023-10-09T11:29:07+0300',
     'archived': False, 'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=87907825',
     'show_logo_in_search': None, 'insider_interview': None, 'url': 'https://api.hh.ru/vacancies/87907825?host=hh.ru',
     'alternate_url': 'https://hh.ru/vacancy/87907825', 'relations': [],
     'employer': {'id': '9130943', 'name': 'EC Pascal', 'url': 'https://api.hh.ru/employers/9130943',
                  'alternate_url': 'https://hh.ru/employer/9130943',
                  'logo_urls': {'original': 'https://hhcdn.ru/employer-logo-original/1053900.png',
                                '90': 'https://hhcdn.ru/employer-logo/5836241.png',
                                '240': 'https://hhcdn.ru/employer-logo/5836242.png'},
                  'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=9130943', 'accredited_it_employer': False,
                  'trusted': True}, 'snippet': {'requirement': None, 'responsibility': None}, 'contacts': None,
     'schedule': {'id': 'flexible', 'name': 'Гибкий график'}, 'working_days': [], 'working_time_intervals': [
        {'id': 'from_four_to_six_hours_in_a_day', 'name': 'Можно работать сменами по\xa04–6 часов в\xa0день'}],
     'working_time_modes': [{'id': 'start_after_sixteen', 'name': 'Можно начинать работать после 16:00'}],
     'accept_temporary': False, 'professional_roles': [{'id': '132', 'name': 'Учитель, преподаватель, педагог'}],
     'accept_incomplete_resumes': False, 'experience': {'id': 'between1And3', 'name': 'От 1 года до 3 лет'},
     'employment': {'id': 'part', 'name': 'Частичная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False},
    {'id': '88469467', 'premium': False, 'name': 'Торговый представитель (кондитерские изделия)', 'department': None,
     'has_test': False, 'response_letter_required': False,
     'area': {'id': '88', 'name': 'Казань', 'url': 'https://api.hh.ru/areas/88'},
     'salary': {'from': 100000, 'to': 150000, 'currency': 'RUR', 'gross': False},
     'type': {'id': 'open', 'name': 'Открытая'},
     'address': {'city': 'Казань', 'street': 'Тихорецкая улица', 'building': '7к35', 'lat': 55.72928, 'lng': 49.121074,
                 'description': None, 'raw': 'Казань, Тихорецкая улица, 7к35',
                 'metro': {'station_name': 'Аметьево', 'line_name': 'Центральная', 'station_id': '49.275',
                           'line_id': '49', 'lat': 55.765346, 'lng': 49.165083}, 'metro_stations': [
             {'station_name': 'Аметьево', 'line_name': 'Центральная', 'station_id': '49.275', 'line_id': '49',
              'lat': 55.765346, 'lng': 49.165083}], 'id': '13204489'}, 'response_url': None,
     'sort_point_distance': None, 'published_at': '2023-10-20T17:27:03+0300', 'created_at': '2023-10-20T17:27:03+0300',
     'archived': False, 'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=88469467',
     'show_logo_in_search': None, 'insider_interview': None, 'url': 'https://api.hh.ru/vacancies/88469467?host=hh.ru',
     'alternate_url': 'https://hh.ru/vacancy/88469467', 'relations': [],
     'employer': {'id': '1060821', 'name': 'Рост Развитие Решение', 'url': 'https://api.hh.ru/employers/1060821',
                  'alternate_url': 'https://hh.ru/employer/1060821',
                  'logo_urls': {'90': 'https://hhcdn.ru/employer-logo/874868.jpeg',
                                '240': 'https://hhcdn.ru/employer-logo/874869.jpeg',
                                'original': 'https://hhcdn.ru/employer-logo-original/85446.jpg'},
                  'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=1060821', 'accredited_it_employer': False,
                  'trusted': True}, 'snippet': {
        'requirement': 'Желателен опыт продаж в пищевом сегменте. Активность, коммуникабельность. Желание обучаться. Мобильность.',
        'responsibility': 'Привлечение новых торговых точек. Работа с существующими торговыми точками. Организация отгрузок и оплат.'},
     'contacts': None, 'schedule': {'id': 'fullDay', 'name': 'Полный день'}, 'working_days': [],
     'working_time_intervals': [], 'working_time_modes': [], 'accept_temporary': False,
     'professional_roles': [{'id': '129', 'name': 'Торговый представитель'}], 'accept_incomplete_resumes': False,
     'experience': {'id': 'between1And3', 'name': 'От 1 года до 3 лет'},
     'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False},
    {'id': '87542041', 'premium': False, 'name': 'Удаленный диспетчер чатов (в Яндекс)', 'department': None,
     'has_test': False, 'response_letter_required': False,
     'area': {'id': '113', 'name': 'Россия', 'url': 'https://api.hh.ru/areas/113'},
     'salary': {'from': 30000, 'to': 44000, 'currency': 'RUR', 'gross': True},
     'type': {'id': 'open', 'name': 'Открытая'}, 'address': None, 'response_url': None, 'sort_point_distance': None,
     'published_at': '2023-09-29T18:19:52+0300', 'created_at': '2023-09-29T18:19:52+0300', 'archived': False,
     'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=87542041', 'show_logo_in_search': None,
     'insider_interview': None, 'url': 'https://api.hh.ru/vacancies/87542041?host=hh.ru',
     'alternate_url': 'https://hh.ru/vacancy/87542041', 'relations': [],
     'employer': {'id': '1740', 'name': 'Яндекс', 'url': 'https://api.hh.ru/employers/1740',
                  'alternate_url': 'https://hh.ru/employer/1740',
                  'logo_urls': {'90': 'https://hhcdn.ru/employer-logo/3790847.png',
                                '240': 'https://hhcdn.ru/employer-logo/3790848.png',
                                'original': 'https://hhcdn.ru/employer-logo-original/837491.png'},
                  'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=1740', 'accredited_it_employer': False,
                  'trusted': True}, 'snippet': {
        'requirement': 'Способен работать в команде. Способен принимать решения самостоятельно. Готов учиться и узнавать новое. Опыт работы в колл-центре или службе...',
        'responsibility': 'Работать с клиентами или партнерами для решения разнообразных ситуаций. Совершать звонки по их обращениям и давать письменные ответы. '},
     'contacts': None, 'schedule': {'id': 'remote', 'name': 'Удаленная работа'}, 'working_days': [],
     'working_time_intervals': [],
     'working_time_modes': [{'id': 'start_after_sixteen', 'name': 'Можно начинать работать после 16:00'}],
     'accept_temporary': False, 'professional_roles': [{'id': '40', 'name': 'Другое'}],
     'accept_incomplete_resumes': True, 'experience': {'id': 'noExperience', 'name': 'Нет опыта'},
     'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False},
    {'id': '87386248', 'premium': False, 'name': 'Менеджер по продажам', 'department': None, 'has_test': False,
     'response_letter_required': False, 'area': {'id': '160', 'name': 'Алматы', 'url': 'https://api.hh.ru/areas/160'},
     'salary': {'from': 350000, 'to': 700000, 'currency': 'KZT', 'gross': True},
     'type': {'id': 'open', 'name': 'Открытая'}, 'address': None, 'response_url': None, 'sort_point_distance': None,
     'published_at': '2023-09-27T07:27:44+0300', 'created_at': '2023-09-27T07:27:44+0300', 'archived': False,
     'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=87386248', 'insider_interview': None,
     'url': 'https://api.hh.ru/vacancies/87386248?host=hh.ru', 'alternate_url': 'https://hh.ru/vacancy/87386248',
     'relations': [],
     'employer': {'id': '10226792', 'name': 'Логистика-Т', 'url': 'https://api.hh.ru/employers/10226792',
                  'alternate_url': 'https://hh.ru/employer/10226792', 'logo_urls': None,
                  'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=10226792', 'accredited_it_employer': False,
                  'trusted': True}, 'snippet': {
        'requirement': 'Коммуникабельность. Желание зарабатывать и активно развиваться. Любовь к продажам. Клиентоориентированность. Навыки делового общения, уверенное пользование ПК. Условия: \u200b\u200b\u200b\u200b\u200b\u200bВысокий уровень дохода...',
        'responsibility': 'Привлечение клиентов через холодные звонки. Развитие закрепленной клиентской базы. Заключение и сопровождение договоров. Консультирование клиентов по услугам компании. '},
     'contacts': None, 'schedule': {'id': 'fullDay', 'name': 'Полный день'}, 'working_days': [],
     'working_time_intervals': [], 'working_time_modes': [], 'accept_temporary': False,
     'professional_roles': [{'id': '70', 'name': 'Менеджер по продажам, менеджер по работе с клиентами'}],
     'accept_incomplete_resumes': False, 'experience': {'id': 'noExperience', 'name': 'Нет опыта'},
     'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False},
    {'id': '88230920', 'premium': False, 'name': 'Оператор контактного центра на входящую линию (удаленно)',
     'department': {'id': 'mgfn-3127-call', 'name': 'МегаФон, Call-центр'}, 'has_test': False,
     'response_letter_required': False, 'area': {'id': '113', 'name': 'Россия', 'url': 'https://api.hh.ru/areas/113'},
     'salary': {'from': 40000, 'to': None, 'currency': 'RUR', 'gross': True},
     'type': {'id': 'open', 'name': 'Открытая'}, 'address': None, 'response_url': None, 'sort_point_distance': None,
     'published_at': '2023-10-16T14:16:24+0300', 'created_at': '2023-10-16T14:16:24+0300', 'archived': False,
     'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=88230920',
     'branding': {'type': 'MAKEUP', 'tariff': None}, 'show_logo_in_search': True, 'insider_interview': None,
     'url': 'https://api.hh.ru/vacancies/88230920?host=hh.ru', 'alternate_url': 'https://hh.ru/vacancy/88230920',
     'relations': [], 'employer': {'id': '3127', 'name': 'МегаФон', 'url': 'https://api.hh.ru/employers/3127',
                                   'alternate_url': 'https://hh.ru/employer/3127',
                                   'logo_urls': {'90': 'https://hhcdn.ru/employer-logo/3747371.png',
                                                 '240': 'https://hhcdn.ru/employer-logo/3747372.png',
                                                 'original': 'https://hhcdn.ru/employer-logo-original/826622.png'},
                                   'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=3127',
                                   'accredited_it_employer': False, 'trusted': True}, 'snippet': {
        'requirement': 'Готовность помогать и находить контакт с людьми. Уверенность при использовании компьютера. Оборудование для удаленной работы дома (компьютер- Windows 8 и...',
        'responsibility': 'Консультировать клиентов по тарифным планам, услугам, балансу и начислениям (общение с нашими действующими абонентами, только входящие звонки). Помогать в выборе...'},
     'contacts': None, 'schedule': {'id': 'fullDay', 'name': 'Полный день'}, 'working_days': [],
     'working_time_intervals': [
         {'id': 'from_four_to_six_hours_in_a_day', 'name': 'Можно работать сменами по\xa04–6 часов в\xa0день'}],
     'working_time_modes': [{'id': 'start_after_sixteen', 'name': 'Можно начинать работать после 16:00'}],
     'accept_temporary': False,
     'professional_roles': [{'id': '83', 'name': 'Оператор call-центра, специалист контактного центра'}],
     'accept_incomplete_resumes': True, 'experience': {'id': 'noExperience', 'name': 'Нет опыта'},
     'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False},
    {'id': '87965048', 'premium': False, 'name': 'Менеджер по работе с клиентами', 'department': None,
     'has_test': False, 'response_letter_required': False,
     'area': {'id': '159', 'name': 'Астана', 'url': 'https://api.hh.ru/areas/159'},
     'salary': {'from': 200000, 'to': None, 'currency': 'KZT', 'gross': False},
     'type': {'id': 'open', 'name': 'Открытая'},
     'address': {'city': 'Нур-Султан (Астана)', 'street': 'проспект Мангилик Ел', 'building': '28', 'lat': 51.110777,
                 'lng': 71.433412, 'description': None, 'raw': 'Нур-Султан (Астана), проспект Мангилик Ел, 28',
                 'metro': None, 'metro_stations': [], 'id': '7438244'}, 'response_url': None,
     'sort_point_distance': None, 'published_at': '2023-10-10T10:30:24+0300', 'created_at': '2023-10-10T10:30:24+0300',
     'archived': False, 'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=87965048',
     'insider_interview': None, 'url': 'https://api.hh.ru/vacancies/87965048?host=hh.ru',
     'alternate_url': 'https://hh.ru/vacancy/87965048', 'relations': [],
     'employer': {'id': '4571497', 'name': 'MaxxFine', 'url': 'https://api.hh.ru/employers/4571497',
                  'alternate_url': 'https://hh.ru/employer/4571497', 'logo_urls': None,
                  'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=4571497', 'accredited_it_employer': False,
                  'trusted': True},
     'snippet': {'requirement': 'Ответственность. Коммуникабельность. Работа в команде. Многозадачность.',
                 'responsibility': 'Просчитывать проекты. Курирование работы всего офиса. Встречать посетителей. Документация. Презентация товара премиум класса. Грамотная устная и письменная речь.'},
     'contacts': None, 'schedule': {'id': 'fullDay', 'name': 'Полный день'}, 'working_days': [],
     'working_time_intervals': [], 'working_time_modes': [], 'accept_temporary': False,
     'professional_roles': [{'id': '70', 'name': 'Менеджер по продажам, менеджер по работе с клиентами'}],
     'accept_incomplete_resumes': False, 'experience': {'id': 'noExperience', 'name': 'Нет опыта'},
     'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False},
    {'id': '83817516', 'premium': False, 'name': 'Продавец-консультант продукции премиум-класса в ТЦ Светлановский',
     'department': None, 'has_test': False, 'response_letter_required': False,
     'area': {'id': '2', 'name': 'Санкт-Петербург', 'url': 'https://api.hh.ru/areas/2'},
     'salary': {'from': 60000, 'to': 120000, 'currency': 'RUR', 'gross': True},
     'type': {'id': 'open', 'name': 'Открытая'},
     'address': {'city': 'Санкт-Петербург', 'street': 'проспект Энгельса', 'building': '33к1', 'lat': 60.00965418095496,
                 'lng': 30.326151271068593, 'description': None, 'raw': 'Санкт-Петербург, проспект Энгельса, 33к1',
                 'metro': None, 'metro_stations': [], 'id': '13827469'}, 'response_url': None,
     'sort_point_distance': None, 'published_at': '2023-10-25T14:58:29+0300', 'created_at': '2023-10-25T14:58:29+0300',
     'archived': False, 'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=83817516',
     'show_logo_in_search': None, 'insider_interview': None, 'url': 'https://api.hh.ru/vacancies/83817516?host=hh.ru',
     'alternate_url': 'https://hh.ru/vacancy/83817516', 'relations': [],
     'employer': {'id': '1910225', 'name': 'Aurum Queen', 'url': 'https://api.hh.ru/employers/1910225',
                  'alternate_url': 'https://hh.ru/employer/1910225',
                  'logo_urls': {'original': 'https://hhcdn.ru/employer-logo-original/709384.png',
                                '90': 'https://hhcdn.ru/employer-logo/3278652.png',
                                '240': 'https://hhcdn.ru/employer-logo/3278653.png'},
                  'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=1910225', 'accredited_it_employer': False,
                  'trusted': True}, 'snippet': {
        'requirement': 'Смелый в общении человек. Ответственность‚ настойчивость‚ честность. Опыт работы в продажах. Желание работать и зарабатывать много.',
        'responsibility': 'Презентация и продажа продукции премиум-класса. Работа с постоянными клиентами и активное привлечение новых.'},
     'contacts': None, 'schedule': {'id': 'fullDay', 'name': 'Полный день'}, 'working_days': [],
     'working_time_intervals': [], 'working_time_modes': [], 'accept_temporary': False,
     'professional_roles': [{'id': '97', 'name': 'Продавец-консультант, продавец-кассир'}],
     'accept_incomplete_resumes': True, 'experience': {'id': 'between1And3', 'name': 'От 1 года до 3 лет'},
     'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False},
    {'id': '88586523', 'premium': False, 'name': 'Водитель-экспедитор', 'department': None, 'has_test': False,
     'response_letter_required': False, 'area': {'id': '1002', 'name': 'Минск', 'url': 'https://api.hh.ru/areas/1002'},
     'salary': {'from': 2400, 'to': 5200, 'currency': 'BYR', 'gross': True}, 'type': {'id': 'open', 'name': 'Открытая'},
     'address': None, 'response_url': None, 'sort_point_distance': None, 'published_at': '2023-10-24T13:56:51+0300',
     'created_at': '2023-10-24T13:56:51+0300', 'archived': False,
     'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=88586523', 'insider_interview': None,
     'url': 'https://api.hh.ru/vacancies/88586523?host=hh.ru', 'alternate_url': 'https://hh.ru/vacancy/88586523',
     'relations': [],
     'employer': {'id': '10457651', 'name': 'Габерник Анна Андреевна', 'url': 'https://api.hh.ru/employers/10457651',
                  'alternate_url': 'https://hh.ru/employer/10457651', 'logo_urls': None,
                  'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=10457651', 'accredited_it_employer': False,
                  'trusted': True}, 'snippet': {'requirement': None,
                                                'responsibility': 'До 40 лет ,т.к нужно переносить товар из машины в пункт самовывоза.'},
     'contacts': None, 'schedule': {'id': 'fullDay', 'name': 'Полный день'}, 'working_days': [],
     'working_time_intervals': [], 'working_time_modes': [], 'accept_temporary': True,
     'professional_roles': [{'id': '21', 'name': 'Водитель'}], 'accept_incomplete_resumes': False,
     'experience': {'id': 'between1And3', 'name': 'От 1 года до 3 лет'},
     'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False},
    {'id': '88177962', 'premium': False, 'name': 'Менеджер по продажам', 'department': None, 'has_test': False,
     'response_letter_required': False, 'area': {'id': '160', 'name': 'Алматы', 'url': 'https://api.hh.ru/areas/160'},
     'salary': {'from': 350000, 'to': 700000, 'currency': 'KZT', 'gross': False},
     'type': {'id': 'open', 'name': 'Открытая'},
     'address': {'city': 'Алматы', 'street': 'Армянская улица', 'building': '7А', 'lat': 43.230076, 'lng': 76.962883,
                 'description': None, 'raw': 'Алматы, Армянская улица, 7А', 'metro': None, 'metro_stations': [],
                 'id': '13013847'}, 'response_url': None, 'sort_point_distance': None,
     'published_at': '2023-10-14T12:49:22+0300', 'created_at': '2023-10-14T12:49:22+0300', 'archived': False,
     'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=88177962', 'show_logo_in_search': None,
     'insider_interview': None, 'url': 'https://api.hh.ru/vacancies/88177962?host=hh.ru',
     'alternate_url': 'https://hh.ru/vacancy/88177962', 'relations': [],
     'employer': {'id': '9701740', 'name': 'Тлесова', 'url': 'https://api.hh.ru/employers/9701740',
                  'alternate_url': 'https://hh.ru/employer/9701740',
                  'logo_urls': {'240': 'https://hhcdn.ru/employer-logo/6348195.png',
                                '90': 'https://hhcdn.ru/employer-logo/6348194.png',
                                'original': 'https://hhcdn.ru/employer-logo-original/1181942.png'},
                  'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=9701740', 'accredited_it_employer': False,
                  'trusted': True}, 'snippet': {
        'requirement': 'Активного и позитивного человека. Умеющего работать с возражениями. Есть аналогичный опыт работы в телемаркетинге, несложных продажах по телефону от 1...',
        'responsibility': 'Обработка только входящих теплых заявок . Работа по скрипту и квалификация клиентов. Согласование встречи между нашим с клиентом, который прошел квалификацию...'},
     'contacts': None, 'schedule': {'id': 'fullDay', 'name': 'Полный день'}, 'working_days': [],
     'working_time_intervals': [], 'working_time_modes': [], 'accept_temporary': False,
     'professional_roles': [{'id': '70', 'name': 'Менеджер по продажам, менеджер по работе с клиентами'}],
     'accept_incomplete_resumes': False, 'experience': {'id': 'between1And3', 'name': 'От 1 года до 3 лет'},
     'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False},
    {'id': '88361549', 'premium': False, 'name': 'Менеджер по продажам', 'department': None, 'has_test': False,
     'response_letter_required': False, 'area': {'id': '1002', 'name': 'Минск', 'url': 'https://api.hh.ru/areas/1002'},
     'salary': {'from': 1500, 'to': None, 'currency': 'BYR', 'gross': False},
     'type': {'id': 'open', 'name': 'Открытая'},
     'address': {'city': 'Минск', 'street': 'проспект Газеты Звязда', 'building': '47', 'lat': 53.861044,
                 'lng': 27.465451, 'description': None, 'raw': 'Минск, проспект Газеты Звязда, 47',
                 'metro': {'station_name': 'Малиновка', 'line_name': 'Московская', 'station_id': '62.472',
                           'line_id': '62', 'lat': 53.849722, 'lng': 27.474722}, 'metro_stations': [
             {'station_name': 'Малиновка', 'line_name': 'Московская', 'station_id': '62.472', 'line_id': '62',
              'lat': 53.849722, 'lng': 27.474722},
             {'station_name': 'Петровщина', 'line_name': 'Московская', 'station_id': '62.415', 'line_id': '62',
              'lat': 53.86458, 'lng': 27.485807}], 'id': '13720328'}, 'response_url': None, 'sort_point_distance': None,
     'published_at': '2023-10-18T17:32:02+0300', 'created_at': '2023-10-18T17:32:02+0300', 'archived': False,
     'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=88361549', 'show_logo_in_search': None,
     'insider_interview': None, 'url': 'https://api.hh.ru/vacancies/88361549?host=hh.ru',
     'alternate_url': 'https://hh.ru/vacancy/88361549', 'relations': [],
     'employer': {'id': '10007508', 'name': 'Роялком', 'url': 'https://api.hh.ru/employers/10007508',
                  'alternate_url': 'https://hh.ru/employer/10007508',
                  'logo_urls': {'original': 'https://hhcdn.ru/employer-logo-original/1125159.jpg',
                                '90': 'https://hhcdn.ru/employer-logo/6121225.jpeg',
                                '240': 'https://hhcdn.ru/employer-logo/6121226.jpeg'},
                  'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=10007508', 'accredited_it_employer': False,
                  'trusted': True}, 'snippet': {
        'requirement': 'Желание работать на результат и зарабатывать. Умение выявлять потребности клиентов и умение убеждать. Коммуникабельность, умение находить общий язык. ',
        'responsibility': 'Поиск новых клиентов. Повышение лояльность клиентов. Полное сопровождение клиентов. Рост выручки и рост прибыли. Предоставление документов в бухгалтерию. '},
     'contacts': None, 'schedule': {'id': 'fullDay', 'name': 'Полный день'}, 'working_days': [],
     'working_time_intervals': [], 'working_time_modes': [], 'accept_temporary': False,
     'professional_roles': [{'id': '70', 'name': 'Менеджер по продажам, менеджер по работе с клиентами'}],
     'accept_incomplete_resumes': False, 'experience': {'id': 'noExperience', 'name': 'Нет опыта'},
     'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False},
    {'id': '88245912', 'premium': False, 'name': 'Менеджер по продажам / Менеджер по работе с партнерами',
     'department': None, 'has_test': False, 'response_letter_required': False,
     'area': {'id': '1', 'name': 'Москва', 'url': 'https://api.hh.ru/areas/1'},
     'salary': {'from': 80000, 'to': 100000, 'currency': 'RUR', 'gross': False},
     'type': {'id': 'open', 'name': 'Открытая'}, 'address': None, 'response_url': None, 'sort_point_distance': None,
     'published_at': '2023-10-16T17:39:21+0300', 'created_at': '2023-10-16T17:39:21+0300', 'archived': False,
     'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=88245912', 'show_logo_in_search': None,
     'insider_interview': None, 'url': 'https://api.hh.ru/vacancies/88245912?host=hh.ru',
     'alternate_url': 'https://hh.ru/vacancy/88245912', 'relations': [],
     'employer': {'id': '1551312', 'name': 'UP business', 'url': 'https://api.hh.ru/employers/1551312',
                  'alternate_url': 'https://hh.ru/employer/1551312',
                  'logo_urls': {'90': 'https://hhcdn.ru/employer-logo/2981572.jpeg',
                                '240': 'https://hhcdn.ru/employer-logo/2981573.jpeg',
                                'original': 'https://hhcdn.ru/employer-logo-original/635105.jpg'},
                  'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=1551312', 'accredited_it_employer': False,
                  'trusted': True}, 'snippet': {
        'requirement': 'Опыт работы в сфере активных B2С-продаж от 1 года. Опыт организации и проведения встреч с юридическими лицами. ',
        'responsibility': 'Работа с брокерами в направлении получения заявок на кредитование под залог недвижимости. Проведение встреч с клиентами компании в офисе. '},
     'contacts': None, 'schedule': {'id': 'fullDay', 'name': 'Полный день'}, 'working_days': [],
     'working_time_intervals': [], 'working_time_modes': [], 'accept_temporary': False,
     'professional_roles': [{'id': '70', 'name': 'Менеджер по продажам, менеджер по работе с клиентами'}],
     'accept_incomplete_resumes': False, 'experience': {'id': 'between1And3', 'name': 'От 1 года до 3 лет'},
     'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False},
    {'id': '87579980', 'premium': False, 'name': 'Менеджер по продажам в курьерскую службу "СДЭК"', 'department': None,
     'has_test': False, 'response_letter_required': False,
     'area': {'id': '159', 'name': 'Астана', 'url': 'https://api.hh.ru/areas/159'},
     'salary': {'from': 300000, 'to': 600000, 'currency': 'KZT', 'gross': False},
     'type': {'id': 'open', 'name': 'Открытая'},
     'address': {'city': 'Астана', 'street': 'переулок Жумабека Ташенова', 'building': None, 'lat': 51.153851,
                 'lng': 71.436295, 'description': None, 'raw': 'Астана, переулок Жумабека Ташенова', 'metro': None,
                 'metro_stations': [], 'id': '12360158'}, 'response_url': None, 'sort_point_distance': None,
     'published_at': '2023-10-02T09:12:40+0300', 'created_at': '2023-10-02T09:12:40+0300', 'archived': False,
     'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=87579980', 'insider_interview': None,
     'url': 'https://api.hh.ru/vacancies/87579980?host=hh.ru', 'alternate_url': 'https://hh.ru/vacancy/87579980',
     'relations': [], 'employer': {'id': '9422942', 'name': 'DES', 'url': 'https://api.hh.ru/employers/9422942',
                                   'alternate_url': 'https://hh.ru/employer/9422942', 'logo_urls': None,
                                   'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=9422942',
                                   'accredited_it_employer': False, 'trusted': True}, 'snippet': {
        'requirement': 'Клиентоориентированность. Стрессоустойчивость. Позитивное мышление. Желание расти и обучаться. Бешеная энергия. Грамотная и четкая речь. Знание государственного и русского языков (знание...',
        'responsibility': 'Укрупнение базы клиентов в своём регионе, выявление потребностей клиента. Контроль над выручкой и количеством отгрузок, выяснения причин спада. '},
     'contacts': None, 'schedule': {'id': 'fullDay', 'name': 'Полный день'}, 'working_days': [],
     'working_time_intervals': [], 'working_time_modes': [], 'accept_temporary': False,
     'professional_roles': [{'id': '70', 'name': 'Менеджер по продажам, менеджер по работе с клиентами'}],
     'accept_incomplete_resumes': False, 'experience': {'id': 'noExperience', 'name': 'Нет опыта'},
     'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False},
    {'id': '88540987', 'premium': False, 'name': 'Водитель категория В', 'department': None, 'has_test': False,
     'response_letter_required': False, 'area': {'id': '1002', 'name': 'Минск', 'url': 'https://api.hh.ru/areas/1002'},
     'salary': {'from': 3000, 'to': None, 'currency': 'BYR', 'gross': False},
     'type': {'id': 'open', 'name': 'Открытая'},
     'address': {'city': 'Минск', 'street': 'улица Казинца', 'building': None, 'lat': 53.854039, 'lng': 27.512783,
                 'description': None, 'raw': 'Минск, улица Казинца', 'metro': None, 'metro_stations': [],
                 'id': '13955294'}, 'response_url': None, 'sort_point_distance': None,
     'published_at': '2023-10-23T15:51:57+0300', 'created_at': '2023-10-23T15:51:57+0300', 'archived': False,
     'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=88540987', 'insider_interview': None,
     'url': 'https://api.hh.ru/vacancies/88540987?host=hh.ru', 'alternate_url': 'https://hh.ru/vacancy/88540987',
     'relations': [],
     'employer': {'id': '1459793', 'name': 'ТРАНСИМПЕРИАЛПРОМ', 'url': 'https://api.hh.ru/employers/1459793',
                  'alternate_url': 'https://hh.ru/employer/1459793', 'logo_urls': None,
                  'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=1459793', 'accredited_it_employer': False,
                  'trusted': True}, 'snippet': {
        'requirement': 'Стаж вождения от 3-х лет. Опыт работы в международных грузоперевозках РБ-РФ ОБЯЗАТЕЛЕН!!!',
        'responsibility': 'Контроль погрузочно-разгрузочных работ. Доставка грузов до пунктов назначения.'},
     'contacts': None, 'schedule': {'id': 'fullDay', 'name': 'Полный день'}, 'working_days': [],
     'working_time_intervals': [], 'working_time_modes': [], 'accept_temporary': False,
     'professional_roles': [{'id': '21', 'name': 'Водитель'}], 'accept_incomplete_resumes': False,
     'experience': {'id': 'between3And6', 'name': 'От 3 до 6 лет'},
     'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False}],
       'found': 1472780, 'pages': 100, 'per_page': 20, 'page': 0, 'clusters': None, 'arguments': None, 'fixes': None,
       'suggests': None, 'alternate_url': 'https://hh.ru/search/vacancy?enable_snippets=true'}


# Json to DataFrame
df = pd.json_normalize(json_data)
# with open("/Users/vinsentenkidu/Desktop/SkyPro/api_vac/src/usrs/123/res/sxmk.json", 'r') as file:
#     df = pd.json_normalize(file)
#     df.to_excel("/Users/vinsentenkidu/Desktop/SkyPro/api_vac/src/usrs/123/res/sxmk.xlsx", index=False)

# DataFrame to Excel
# excel_filename = '/Users/vinsentenkidu/Desktop/SkyPro/api_vac/src/usrs/123/res/resres.json'
# df.to_excel(excel_filename, index=False)





pandas.read_json("/Users/vinsentenkidu/Desktop/SkyPro/api_vac/src/usrs/123/res/кура.json").to_excel("output.xlsx")