var = {"id": "88737138", "premium": false, "name": "Семейный водитель", "department": null, "has_test": false,
       "response_letter_required": true, "area": {"id": "1", "name": "Москва", "url": "https://api.hh.ru/areas/1"},
       "salary": {"from": null, "to": 100000, "currency": "RUR", "gross": false},
       "type": {"id": "open", "name": "Открытая"}, "address": null, "response_url": null, "sort_point_distance": null,
       "published_at": "2023-10-27T11:13:17+0300", "created_at": "2023-10-27T11:13:17+0300", "archived": false,
       "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=88737138", "insider_interview": null,
       "url": "https://api.hh.ru/vacancies/88737138?host=hh.ru", "alternate_url": "https://hh.ru/vacancy/88737138",
       "relations": [], "employer": {"id": "9401529", "name": "Алексеева Светлана Игоревна",
                                     "url": "https://api.hh.ru/employers/9401529",
                                     "alternate_url": "https://hh.ru/employer/9401529", "logo_urls": null,
                                     "vacancies_url": "https://api.hh.ru/vacancies?employer_id=9401529",
                                     "accredited_it_employer": false, "trusted": false}, "snippet": {
        "requirement": "Корректность и тактичность в общении, опрятность. Опыт работы личным <highlighttext>водителем</highlighttext> или бизнес такси от 6 лет, стаж вождения более 10...",
        "responsibility": "Обеспечение комфортного сопровождения на автомобиле работодателя и членов его семьи. Поездки по Москве и Московской области. Выполнение поручений. "},
       "contacts": null, "schedule": {"id": "fullDay", "name": "Полный день"}, "working_days": [],
       "working_time_intervals": [], "working_time_modes": [], "accept_temporary": false,
       "professional_roles": [{"id": "21", "name": "Водитель"}], "accept_incomplete_resumes": false,
       "experience": {"id": "moreThan6", "name": "Более 6 лет"},
       "employment": {"id": "full", "name": "Полная занятость"}, "adv_response_url": null, "is_adv_vacancy": false}, {
    "id": "88823735", "premium": false, "name": "Водитель категории В на автомобиле организации", "department": null,
    "has_test": false, "response_letter_required": false,
    "area": {"id": "1", "name": "Москва", "url": "https://api.hh.ru/areas/1"},
    "salary": {"from": 100000, "to": 100000, "currency": "RUR", "gross": false},
    "type": {"id": "open", "name": "Открытая"},
    "address": {"city": "Москва", "street": "Тургеневская площадь", "building": "2", "lat": 55.765311, "lng": 37.635835,
                "description": null, "raw": "Москва, Тургеневская площадь, 2", "metro": null, "metro_stations": [],
                "id": "887671"}, "response_url": null, "sort_point_distance": null,
    "published_at": "2023-10-30T12:27:41+0300", "created_at": "2023-10-30T12:27:41+0300", "archived": false,
    "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=88823735", "insider_interview": null,
    "url": "https://api.hh.ru/vacancies/88823735?host=hh.ru", "alternate_url": "https://hh.ru/vacancy/88823735",
    "relations": [], "employer": {"id": "2695881", "name": "ГКУ Объединенная дирекция Мосгорпарк",
                                  "url": "https://api.hh.ru/employers/2695881",
                                  "alternate_url": "https://hh.ru/employer/2695881", "logo_urls": null,
                                  "vacancies_url": "https://api.hh.ru/vacancies?employer_id=2695881",
                                  "accredited_it_employer": false, "trusted": true}, "snippet": {
        "requirement": "Водительское удостоверение категории B. Опыт работы персональным <highlighttext>водителем</highlighttext> от 3-х лет. Стрессоустойчивость и сдержанность. Профессиональное, быстрое, но безопасное и...",
        "responsibility": "Резюмe толькo с фото. Гoтoвнocть к нeнормировaнному рабoчему дню. Готoвнocть выпoлнять рабочие поручeния руководителя. Управление служебным автомобилем Toyota Camry."},
    "contacts": null, "schedule": {"id": "fullDay", "name": "Полный день"}, "working_days": [],
    "working_time_intervals": [], "working_time_modes": [], "accept_temporary": false,
    "professional_roles": [{"id": "21", "name": "Водитель"}], "accept_incomplete_resumes": false,
    "experience": {"id": "between3And6", "name": "От 3 до 6 лет"},
    "employment": {"id": "full", "name": "Полная занятость"}, "adv_response_url": null, "is_adv_vacancy": false}